#!/usr/bin/env bash
set -e # 에러 발생 시 스크립트 중단

cd _site
git config user.name "JY KIM"
git config user.email "kimorkim@gmail.com"
git add .
git commit -m "Entry-HW Document Update"
git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages